### ISSUE TITLE
NodePublish does not respect mount options

### ISSUE THREAD

**Issue by jsafrane** [kubernetes-sigs/azuredisk-csi-driver#2049]
**What happened**:

`pv.spec.csi.mountOptions` (or `volume_capability.MountVolume.mount_flags` in CSI terms) is respected only in NodeStageVolume call, but it's ignored in `NodePublishVolume`. Is there a reason for that? Few other drivers that I checked do this ([AWS EBS](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/3dde68b07dbca3742208bed288ecb47b9e1050ef/pkg/driver/node.go#L727C1-L733),[ GCP PD](https://github.com/openshift/gcp-pd-csi-driver/blob/269ed09ed82cfaa228b1c913990f3d44b637af37/pkg/gce-pd-csi-driver/node.go#L140-L141))

I can send a pull request if there is no special reason for this behavior.

**Comment by andyzhangx** [comment]
the NodePublish in this CSI driver only do bind mount, how is mountOptions used in bind mount? the `mountOptions` specified in PV is used only in NodeStageVolume which does the actual mount now.

**Comment by jsafrane** [comment]
Some mount options can be used in bind-mount too. From `man mount`:

> [in addition to `ro`] it’s also possible to change nosuid, nodev, noexec, noatime, nodiratime, relatime and nosymfollow VFS entry flags [...]. The other flags (for example filesystem-specific flags) are silently ignored.

Like, it's not a big deal, I just noticed some CSI drivers use mount options passed in NodePublish and some don't. It most probably does not affect anything important now.

(My personal goal is to pass `-o context=<some SELinux context>` as a mount option and NodeStage is enough here)

**Comment by tspearconquest** [comment]
Hi - quick question on this. I have set fstype to xfs and mounted a PV to my pods successfully. In the PV I have set `mountOptions: ["nodev", "noexec", "nosuid"]`. When I get into the node and run `mount`, I can see the filesystem mounted with these mount options. When I get into the pod and run `mount`, I don't see these options.

Since these options can be passed to bind mounts, does it mean that the filesystem will allow exec for files in the pod?

**Comment by tspearconquest** [comment]
Based on the below testing, it seems like the mount options of the source filesystem are being ignored (perhaps not checked by the kernel itself?) due to the bind mount to the pod doesn't have the `noexec` mount option.

I copied the `/usr/bin/mount` binary in my pod (running busybox) to the PV and was able to run `./mount` without any error and see the mounts, just as if I had run the mount command straight from the $PATH.

I propose to reopen this as it would seem that we need these mount options passed to bind mounts for them to properly apply at the pod level.
