### ISSUE TITLE
PVC error while marshaling

### ISSUE THREAD

**Issue by gregmo2413** [kubernetes-sigs/azuredisk-csi-driver#2433]
**What happened**: While trying to create a pod specifying a pvc bound to a static azure nfs file share pv, I received the following error - MountVolume.MountDevice failed for volume "azurefiletest" : rpc error: code = Internal desc = grpc: error while marshaling: string field contains invalid UTF-8

**What you expected to happen**: Pod would mount static nfs file share

**How to reproduce it**: Create a pod specifying a claim to a static nfs file share

**Anything else we need to know?**:

**Environment**:

- CSI Driver version: v1.30.1
- Kubernetes version (use `kubectl version`): v1.29.4
- OS (e.g. from /etc/os-release): Ubuntu 22.04.4 LTS
- Kernel (e.g. `uname -a`): 5.15.0-1053-azure-fips
[azurefile_github_issue.txt](https://github.com/user-attachments/files/16396528/azurefile_github_issue.txt)

- Install tools:
- Others:

**Comment by andyzhangx** [comment]
@gregmo2413 can you check your pv config, especially the `volumeHandle` value, it may contain illegal char, e.g. remove `{` and last char.

**Comment by andyzhangx** [comment]
@gregmo2413 can you check your pv config, especially the `volumeHandle` value, it may contain illegal char, e.g. remove `{` and last char.

**Comment by gregmo2413** [comment]
I removed the curly brace and tried again. Same result.

**Comment by andyzhangx** [comment]
@gregmo2413 there is invalid UTF-8 chars in your pv config per the error msg, can you  check that by yourself?

 Here's another example in Python using the utf8validator library:
```
import utf8validator

def contains_invalid_utf8(s):
    try:
        utf8validator.validate_bytes(s.encode('utf-8'))
        return False
    except utf8validator.InvalidUTF8:
        return True
```
This function returns True if the string s contains invalid UTF-8 byte sequences, and False otherwise. You can call this function with your string as an argument to check if it contains invalid UTF-8.

Keep in mind that these methods are not foolproof and may not catch all cases of invalid UTF-8. It's always a good idea to test your code with a variety of inputs to ensure that it works correctly.

**Comment by gregmo2413** [comment]
I created a new test deployment yaml file from my original yaml file. Instead of using a PVC, I used an inline volume configuration instead. This time I was able to successfully mount the azure nfs file share. I don't believe there was an invalid UTF-8 character in my original yaml file.

Change I made to my original test deployment yaml file:

From:
      volumes:
        - name: cpe-infra-test
          persistentVolumeClaim:
            claimName: pvc-azurefile-test

To:
      volumes:
        - name: cpe-infra-test
          csi:
            driver: file.csi.azure.com
            volumeAttributes:
              subscriptionID: d1ed24b3-3042-4571-acb4-87fdaf764af5
              resourceGroup: rave-cluster-federal-usgovvirginia
              storageAccount: raveclusternfsstore
              shareName: raveclusternfsstore/cpe-infra-test
              protocol: nfs
              server: raveclusternfsstore.file.core.usgovcloudapi.net

**Comment by gregmo2413** [comment]
I used the following simple python script to check the yaml file for invalid utf-8 characters. No invalid utf-8 characters were found.

#! /usr/local/bin/python3

import sys

def verify_utf8(file_path):
    try:
        with open(file_path, 'rb') as file:
            file.read().decode('utf-8')
        print(f"{file_path} does not contain any invalid UTF-8 characters.")
    except UnicodeDecodeError as e:
        print(f"{file_path} contains invalid UTF-8 characters: {e}")

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: python verify_utf8.py <file_path>")
        sys.exit(1)

    file_path = sys.argv[1]
    verify_utf8(file_path)

**Comment by andyzhangx** [comment]
pls remove `nodeStageSecretRef` in pv config, for nfs mount, secret is not needed.

```
    nodeStageSecretRef:
      name: pv-secret-rave-cpe-infra-test
      namespace: rave-cluster-stage
```

**Comment by andyzhangx** [comment]
@gregmo2413 I think the `invalid utf-8 characters` is from your k8s secret, anyway, I am happy it's working

**Comment by matthewerwin** [comment]
@andyzhangx @gregmo2413 following this thread and having seen a similar situation when I was toying around with this the problem. The key value is a base64 encoded binary value and thus it's easy to make the mistake of not realizing it has to be "double-encoded" when applied as a secret.yaml using kubectl -- otherwise when the CSI driver attempts to use the secret value it will simply be binary (and thus not UTF-8). 

You can see that it's double-encoded when following the Azure docs:

This returns a base64 storage key:
`STORAGE_KEY=$(az storage account keys list --resource-group nodeResourceGroupName --account-name myAKSStorageAccount --query "[0].value" -o tsv)`

This command does a second layer of base64 encoding as it is persisted to a secret:
`kubectl create secret generic azure-secret --from-literal=azurestorageaccountname=myAKSStorageAccount --from-literal=azurestorageaccountkey=$STORAGE_KEY`

**Comment by ajmyyra** [comment]
@matthewerwin: Thank you! It seems to be similar thing with other credentials and CSI drivers (Ceph in this case) that also needs this double base64 encoding treatment in secrets. The error wasn't the cleared but thankfully searching for it led me here.
